name: Run tests
on:
  push:
    paths:
      - 'src/**'
    tags-ignore:
      - '*.*'
  pull_request:
    paths:
      - 'src/**'
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: c-hive/gha-yarn-cache@v1
      - run: yarn
      - run: yarn test
